-- Generated candidate baseline from live reference database.
-- Generated by: scripts/generate_b18_baseline_candidate.sh
-- This file is a candidate only. Promote it to src/main/resources/db/migration/B18__baseline.sql
-- only after applying it to an empty database and validating application startup.

SET FOREIGN_KEY_CHECKS = 0;

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `member` (
  `id` bigint NOT NULL,
  `authority` enum('GUEST','USER','ADMIN') DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `loginMethod` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `password` varchar(255) DEFAULT NULL,
  `phoneNumber` varchar(30) DEFAULT NULL,
  `birthDate` date DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `address` varchar(120) DEFAULT NULL,
  `addressDetail` varchar(120) DEFAULT NULL,
  `profileImageUrl` varchar(500) DEFAULT NULL,
  `notificationEnabled` bit(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKob8kqyqqgmefl0aco34akdtpe` (`email`),
  UNIQUE KEY `uk_member_name` (`name`),
  KEY `idx_member_phone_number` (`phoneNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_block` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `blocker_id` bigint NOT NULL,
  `blocked_id` bigint NOT NULL,
  `regTime` datetime(6) DEFAULT NULL,
  `updateTime` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_block_blocker_blocked` (`blocker_id`,`blocked_id`),
  KEY `idx_user_block_blocker_regtime` (`blocker_id`,`regTime`),
  KEY `idx_user_block_blocked_regtime` (`blocked_id`,`regTime`),
  CONSTRAINT `fk_user_block_blocked` FOREIGN KEY (`blocked_id`) REFERENCES `member` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_block_blocker` FOREIGN KEY (`blocker_id`) REFERENCES `member` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `bookmark` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `recipe_ID` bigint NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `folder_name` varchar(60) DEFAULT NULL,
  `tag_name` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK5uegdxr9ddv4k7j9q2rx1sh0p` (`user_id`,`recipe_ID`),
  UNIQUE KEY `UKkp8jnjy8t7vqe8phe3avvmn2d` (`email`,`recipe_ID`),
  KEY `FKkdh419qvxulj97omjdnxk8wq7` (`recipe_ID`),
  CONSTRAINT `FK3ogdxsxa4tx6vndyvpk1fk1am` FOREIGN KEY (`user_id`) REFERENCES `member` (`id`),
  CONSTRAINT `FK72ux9h903oo291lnwdpxj7r1e` FOREIGN KEY (`email`) REFERENCES `member` (`email`),
  CONSTRAINT `FKkdh419qvxulj97omjdnxk8wq7` FOREIGN KEY (`recipe_ID`) REFERENCES `recipe_info` (`row_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_activity_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `action` varchar(80) NOT NULL,
  `detail` varchar(500) DEFAULT NULL,
  `regTime` datetime(6) DEFAULT NULL,
  `updateTime` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user_activity_user_regtime` (`user_id`,`regTime`),
  KEY `idx_user_activity_action_regtime` (`action`,`regTime`),
  CONSTRAINT `fk_user_activity_user` FOREIGN KEY (`user_id`) REFERENCES `member` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `member_seq` (
  `next_val` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `board` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `regTime` datetime(6) DEFAULT NULL,
  `updateTime` datetime(6) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `modifiedBy` varchar(255) DEFAULT NULL,
  `commentCount` bigint DEFAULT NULL,
  `contents` longtext,
  `likeCount` bigint DEFAULT NULL,
  `state` varchar(1) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `views` bigint DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `section_id` bigint DEFAULT NULL,
  `is_hidden_by_report` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  KEY `idx_board_state_reg_time` (`state`,`regTime`),
  KEY `idx_board_state_title` (`state`,`title`),
  KEY `idx_board_user_id` (`user_id`),
  KEY `idx_board_state_section_reg_time` (`state`,`section_id`,`regTime`),
  KEY `idx_board_state_like_count` (`state`,`likeCount`),
  KEY `FKofjdicxhplloyi17wtysmi5a9` (`section_id`),
  KEY `idx_board_state_hidden_reg_time` (`state`,`is_hidden_by_report`,`regTime`),
  KEY `idx_board_state_hidden_section_reg_time` (`state`,`is_hidden_by_report`,`section_id`,`regTime`),
  KEY `idx_board_state_hidden_like_count_reg_time` (`state`,`is_hidden_by_report`,`likeCount`,`regTime`),
  CONSTRAINT `FKfyf1fchnby6hndhlfaidier1r` FOREIGN KEY (`user_id`) REFERENCES `member` (`id`),
  CONSTRAINT `FKofjdicxhplloyi17wtysmi5a9` FOREIGN KEY (`section_id`) REFERENCES `board_section` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `comments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `regTime` datetime(6) DEFAULT NULL,
  `updateTime` datetime(6) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `modifiedBy` varchar(255) DEFAULT NULL,
  `contents` varchar(255) NOT NULL,
  `state` varchar(1) NOT NULL,
  `post_id` bigint NOT NULL,
  `parent_id` bigint DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKhelkafkqj798li57pcpbvjug` (`user_id`),
  KEY `idx_comments_post_state` (`post_id`,`state`),
  KEY `idx_comments_post_reg_time` (`post_id`,`regTime`),
  KEY `idx_comments_parent_id` (`parent_id`),
  KEY `idx_comments_post_parent_reg_time` (`post_id`,`parent_id`,`regTime`),
  CONSTRAINT `FK1yvn1vr3w48cihunxlrwt28f2` FOREIGN KEY (`parent_id`) REFERENCES `comments` (`id`),
  CONSTRAINT `FKhelkafkqj798li57pcpbvjug` FOREIGN KEY (`user_id`) REFERENCES `member` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FKqnr1nghwvbv9ehguo5adeg0hy` FOREIGN KEY (`post_id`) REFERENCES `board` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `likes` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `post_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKacbo1sjg3w5aveq7ola78mkxe` (`user_id`,`post_id`),
  KEY `FK6b0cfsvjv3fldh8tf885xnr9i` (`post_id`),
  CONSTRAINT `FK6b0cfsvjv3fldh8tf885xnr9i` FOREIGN KEY (`post_id`) REFERENCES `board` (`id`),
  CONSTRAINT `FKo8m7ie9t84ebyud050axtdcew` FOREIGN KEY (`user_id`) REFERENCES `member` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `board_scrap` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `board_id` bigint NOT NULL,
  `regTime` datetime(6) DEFAULT NULL,
  `updateTime` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_board_scrap_user_board` (`user_id`,`board_id`),
  KEY `idx_board_scrap_user_regtime` (`user_id`,`regTime`),
  KEY `idx_board_scrap_board_regtime` (`board_id`,`regTime`),
  CONSTRAINT `fk_board_scrap_board` FOREIGN KEY (`board_id`) REFERENCES `board` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_board_scrap_user` FOREIGN KEY (`user_id`) REFERENCES `member` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `board_report` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `board_id` bigint NOT NULL,
  `reporter_id` bigint NOT NULL,
  `reason` varchar(30) NOT NULL,
  `details` varchar(500) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'OPEN',
  `processed_by` bigint DEFAULT NULL,
  `processed_note` varchar(500) DEFAULT NULL,
  `processed_time` datetime(6) DEFAULT NULL,
  `priority_score` int NOT NULL DEFAULT '0',
  `is_suspicious` bit(1) NOT NULL DEFAULT b'0',
  `regTime` datetime(6) DEFAULT NULL,
  `updateTime` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_board_report_board_reporter` (`board_id`,`reporter_id`),
  KEY `idx_board_report_status_regtime` (`status`,`regTime`),
  KEY `idx_board_report_reporter_regtime` (`reporter_id`,`regTime`),
  KEY `idx_board_report_board_regtime` (`board_id`,`regTime`),
  KEY `idx_board_report_processed_by_time` (`processed_by`,`processed_time`),
  KEY `idx_board_report_status_priority_regtime` (`status`,`is_suspicious`,`priority_score`,`regTime`),
  CONSTRAINT `fk_board_report_board` FOREIGN KEY (`board_id`) REFERENCES `board` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_board_report_processed_by` FOREIGN KEY (`processed_by`) REFERENCES `member` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_board_report_reporter` FOREIGN KEY (`reporter_id`) REFERENCES `member` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `board_policy` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `featuredLikeThreshold` int NOT NULL,
  `thumbnail_display_mode` varchar(20) NOT NULL DEFAULT 'LEFT',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `board_section` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `active` bit(1) NOT NULL,
  `displayOrder` int NOT NULL,
  `sectionKey` varchar(50) NOT NULL,
  `sectionName` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKac9r5ywwmr3xvj59nqtu38mv8` (`sectionKey`),
  KEY `idx_board_section_display_order` (`displayOrder`),
  KEY `idx_board_section_active_display_order` (`active`,`displayOrder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `images` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `imgUrl` varchar(500) NOT NULL,
  `post_id` bigint DEFAULT NULL,
  `regTime` datetime(6) DEFAULT NULL,
  `updateTime` datetime(6) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `modifiedBy` varchar(255) DEFAULT NULL,
  `originalFilename` varchar(255) DEFAULT NULL,
  `savedFilename` varchar(255) DEFAULT NULL,
  `contentType` varchar(100) DEFAULT NULL,
  `fileSize` bigint DEFAULT NULL,
  `status` enum('ATTACHED','DELETED','TEMP') DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_images_post_id_status` (`post_id`,`status`),
  KEY `idx_images_url_status` (`imgUrl`,`status`),
  CONSTRAINT `FKb235b9pdmmamu4fcmjclrjep7` FOREIGN KEY (`post_id`) REFERENCES `board` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `board_image` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `board_id` bigint NOT NULL,
  `image_id` bigint NOT NULL,
  `regTime` datetime(6) DEFAULT NULL,
  `updateTime` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_board_image_board_id_image_id` (`board_id`,`image_id`),
  KEY `idx_board_image_board_id` (`board_id`),
  KEY `idx_board_image_image_id` (`image_id`),
  CONSTRAINT `fk_board_image_board` FOREIGN KEY (`board_id`) REFERENCES `board` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_board_image_image` FOREIGN KEY (`image_id`) REFERENCES `images` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `files` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `fileName` varchar(255) DEFAULT NULL,
  `post_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK2a3a5q79k5rp55nudorci0u0v` (`post_id`),
  CONSTRAINT `FK2a3a5q79k5rp55nudorci0u0v` FOREIGN KEY (`post_id`) REFERENCES `board` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `notification` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `receiver_id` bigint NOT NULL,
  `actor_id` bigint NOT NULL,
  `board_id` bigint NOT NULL,
  `comment_id` bigint DEFAULT NULL,
  `type` varchar(30) NOT NULL,
  `content_preview` varchar(255) DEFAULT NULL,
  `is_read` bit(1) NOT NULL DEFAULT b'0',
  `read_time` datetime(6) DEFAULT NULL,
  `regTime` datetime(6) DEFAULT NULL,
  `updateTime` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_notification_receiver_read_regtime` (`receiver_id`,`is_read`,`regTime`),
  KEY `idx_notification_receiver_regtime` (`receiver_id`,`regTime`),
  KEY `idx_notification_board_comment` (`board_id`,`comment_id`),
  KEY `fk_notification_actor` (`actor_id`),
  KEY `fk_notification_comment` (`comment_id`),
  CONSTRAINT `fk_notification_actor` FOREIGN KEY (`actor_id`) REFERENCES `member` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_notification_board` FOREIGN KEY (`board_id`) REFERENCES `board` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_notification_comment` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_notification_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `member` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `board_stats` (
  `board_id` bigint NOT NULL,
  `total_views` bigint NOT NULL DEFAULT '0',
  `total_likes` bigint NOT NULL DEFAULT '0',
  `total_comments` bigint NOT NULL DEFAULT '0',
  `score` decimal(18,6) NOT NULL DEFAULT '0.000000',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`board_id`),
  KEY `idx_board_stats_score` (`score`),
  KEY `idx_board_stats_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `board_popular_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `snapshot_type` varchar(40) NOT NULL,
  `section_key` varchar(40) NOT NULL DEFAULT '',
  `rank_no` int NOT NULL,
  `board_id` bigint NOT NULL,
  `score` decimal(18,6) NOT NULL DEFAULT '0.000000',
  `generated_at` datetime(6) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_board_popular_snapshot_slot` (`snapshot_type`,`section_key`,`rank_no`,`generated_at`),
  KEY `idx_board_popular_snapshot_lookup` (`snapshot_type`,`section_key`,`expires_at`,`rank_no`),
  KEY `idx_board_popular_snapshot_board` (`board_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `recipe_stats` (
  `recipe_id` bigint NOT NULL,
  `total_views` bigint NOT NULL DEFAULT '0',
  `total_likes` bigint NOT NULL DEFAULT '0',
  `total_bookmarks` bigint NOT NULL DEFAULT '0',
  `score` decimal(18,6) NOT NULL DEFAULT '0.000000',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`recipe_id`),
  KEY `idx_recipe_stats_score` (`score`),
  KEY `idx_recipe_stats_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `recipe_reco_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `slot_date` date NOT NULL,
  `slot_type` varchar(20) NOT NULL,
  `rank_no` int NOT NULL,
  `recipe_id` bigint NOT NULL,
  `score` decimal(18,6) NOT NULL DEFAULT '0.000000',
  `generated_at` datetime(6) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_recipe_reco_snapshot_slot` (`slot_date`,`slot_type`,`rank_no`),
  KEY `idx_recipe_reco_snapshot_lookup` (`slot_date`,`slot_type`,`expires_at`,`rank_no`),
  KEY `idx_recipe_reco_snapshot_recipe` (`recipe_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `recipe_review` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `recipe_row_num` bigint NOT NULL,
  `rating` int NOT NULL,
  `contents` varchar(500) DEFAULT NULL,
  `regTime` datetime(6) DEFAULT NULL,
  `updateTime` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_recipe_review_user_recipe` (`user_id`,`recipe_row_num`),
  KEY `idx_recipe_review_recipe_regtime` (`recipe_row_num`,`regTime`),
  KEY `idx_recipe_review_recipe_rating` (`recipe_row_num`,`rating`),
  KEY `idx_recipe_review_user_regtime` (`user_id`,`regTime`),
  CONSTRAINT `fk_recipe_review_recipe` FOREIGN KEY (`recipe_row_num`) REFERENCES `recipe_info` (`row_NUM`) ON DELETE CASCADE,
  CONSTRAINT `fk_recipe_review_user` FOREIGN KEY (`user_id`) REFERENCES `member` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `recipe_info` (
  `recipe_ID` bigint DEFAULT NULL,
  `row_NUM` bigint NOT NULL,
  `calorie` varchar(255) DEFAULT NULL,
  `cooking_TIME` varchar(255) DEFAULT NULL,
  `irdnt_CODE` varchar(255) DEFAULT NULL,
  `level_NM` varchar(255) DEFAULT NULL,
  `nation_CODE` varchar(255) DEFAULT NULL,
  `nation_NM` varchar(255) DEFAULT NULL,
  `pc_NM` varchar(255) DEFAULT NULL,
  `qnt` varchar(255) DEFAULT NULL,
  `recipe_NM_KO` varchar(255) DEFAULT NULL,
  `sumry` varchar(255) DEFAULT NULL,
  `ty_CODE` varchar(255) DEFAULT NULL,
  `ty_NM` varchar(255) DEFAULT NULL,
  `img_URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`row_NUM`),
  KEY `idx_recipe_info_recipe_id` (`recipe_ID`),
  KEY `idx_recipe_info_ty_nm` (`ty_NM`),
  KEY `idx_recipe_info_nation_nm` (`nation_NM`),
  KEY `idx_recipe_info_irdnt_code` (`irdnt_CODE`),
  KEY `idx_recipe_info_recipe_nm_ko` (`recipe_NM_KO`),
  KEY `idx_recipe_info_ty_nm_row_num` (`ty_NM`,`row_NUM`),
  KEY `idx_recipe_info_nation_nm_row_num` (`nation_NM`,`row_NUM`),
  KEY `idx_recipe_info_irdnt_code_row_num` (`irdnt_CODE`,`row_NUM`),
  KEY `idx_recipe_info_recipe_nm_ko_row_num` (`recipe_NM_KO`,`row_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `recipe_irdnt` (
  `recipe_ID` bigint DEFAULT NULL,
  `row_NUM` bigint NOT NULL,
  `irdnt_CPCTY` varchar(255) DEFAULT NULL,
  `irdnt_NM` varchar(255) DEFAULT NULL,
  `irdnt_SN` varchar(255) DEFAULT NULL,
  `irdnt_TY_CODE` varchar(255) DEFAULT NULL,
  `irdnt_TY_NM` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`row_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `recipe_crse` (
  `recipe_ID` bigint DEFAULT NULL,
  `row_NUM` bigint NOT NULL,
  `cooking_DC` varchar(255) DEFAULT NULL,
  `cooking_NO` varchar(255) DEFAULT NULL,
  `step_TIP` varchar(255) DEFAULT NULL,
  `img_URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`row_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `recipe_data` (
  `recipe_id` int NOT NULL,
  `calorie` varchar(255) DEFAULT NULL,
  `cooking_time` varchar(255) DEFAULT NULL,
  `irdnt_code` varchar(255) DEFAULT NULL,
  `level_nm` varchar(255) DEFAULT NULL,
  `nation_code` varchar(255) DEFAULT NULL,
  `nation_nm` varchar(255) DEFAULT NULL,
  `pc_nm` varchar(255) DEFAULT NULL,
  `qnt` varchar(255) DEFAULT NULL,
  `recipe_nm_ko` varchar(255) DEFAULT NULL,
  `sumry` varchar(255) DEFAULT NULL,
  `ty_code` varchar(255) DEFAULT NULL,
  `ty_nm` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`recipe_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `recipe_info_seq` (
  `next_val` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `recipe_irdnt_seq` (
  `next_val` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `recipe_crse_seq` (
  `next_val` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

SET FOREIGN_KEY_CHECKS = 1;

-- Required reference rows only.
INSERT INTO board_policy (id, featuredLikeThreshold, thumbnail_display_mode) VALUES (1, 5, 'LEFT');
INSERT INTO board_section (id, sectionKey, sectionName, displayOrder, active) VALUES (1, 'general', '자유', 0, TRUE);

-- Recipe catalog rows are intentionally excluded.
-- Export them from a canonical DB with mysqldump and import them with scripts/import_recipe_catalog.sh.
