package kwh.PublicCookedFood.user.aop;

public enum AccountRecoveryAuditType {
    FIND_EMAIL_SUCCESS,
    FIND_EMAIL_NOT_FOUND,
    RESET_PASSWORD_SUCCESS,
    RESET_PASSWORD_NOT_FOUND,
    RESET_PASSWORD_CODE_MAIL_UNAVAILABLE,
    RESET_PASSWORD_CODE_ISSUED,
    RESET_PASSWORD_CODE_NOT_FOUND_OR_SKIPPED
}
